import React from "react";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import ForbiddenPage from "./app/forbidden/page";
import { buildSectionPage } from "./app/section-page";

describe("feature page content spacing baseline", () => {
  it("keeps desktop feature pages on the shared PageShell spacing model", () => {
    const globalCss = readFileSync(new URL("./app/globals.css", import.meta.url), "utf8");

    expect(globalCss).toContain("--desktop-sidebar-collapsed-width: 86px");
    expect(globalCss).toContain("--desktop-content-padding-inline: clamp(6px, 0.72vw, 12px)");
    expect(globalCss).toContain("--feature-page-outer-gap-block: var(--desktop-content-padding-inline);");
    expect(globalCss).toContain("--feature-page-outer-gap-inline: var(--desktop-content-padding-inline);");
    expect(globalCss).toContain("--feature-page-card-radius: 18px;");
    expect(globalCss).toContain("--feature-page-card-padding: 14px;");
    expect(globalCss).toContain("--feature-page-title-offset-block: var(--feature-page-card-padding);");
    expect(globalCss).toContain("--feature-page-title-offset-inline: var(--feature-page-card-padding);");
    expect(globalCss).toContain("--feature-page-title-content-gap: 0px;");
    expect(globalCss).toContain("--two-column-content-sidebar-width: minmax(220px, 260px);");
    expect(globalCss).toContain("--two-column-content-sidebar-width-compact: minmax(200px, 240px);");
    expect(globalCss).toContain("--two-column-content-column-padding-inline: clamp(16px, 1.6vw, 22px);");
    expect(globalCss).toContain("--two-column-content-column-gap: 0px;");
    expect(globalCss).toContain("--two-column-content-title-gap: 14px;");
    expect(globalCss).toContain("--two-column-content-list-gap: 18px;");
    expect(globalCss).toContain("--two-column-content-divider: 1px solid var(--line);");
    expect(globalCss).toContain(".page-shell,");
    expect(globalCss).toContain("width: 100%");
    expect(globalCss).toContain("max-width: none");
    expect(globalCss).toContain("padding-inline: var(--feature-page-outer-gap-inline)");
    expect(globalCss).toContain("width: calc(100% - var(--desktop-content-padding-inline) - var(--desktop-content-padding-inline))");
    expect(globalCss).toContain(".page-shell__content {");
    expect(globalCss).toContain("gap: 0;");
    expect(globalCss).toContain("background: var(--surface);");
    expect(globalCss).toContain("grid-template-rows: auto minmax(0, 1fr);");
    expect(globalCss).toContain(".app-shell__body > .page-shell {");
    expect(globalCss).toContain("flex: 1 1 auto;");
    expect(globalCss).toContain("padding-top: var(--feature-page-outer-gap-block);");
    expect(globalCss).toContain("padding-bottom: var(--feature-page-outer-gap-block);");
    expect(globalCss).not.toContain("padding-bottom: 28px;");
    expect(globalCss).toContain("overflow: hidden;");
    expect(globalCss).toContain("overflow-y: auto;");
    expect(globalCss).toContain(".page-shell__content:hover");
    expect(globalCss).toContain("padding: var(--feature-page-title-offset-block) var(--feature-page-title-offset-inline);");
    expect(globalCss).toContain("border-radius: var(--feature-page-card-radius) var(--feature-page-card-radius) 0 0;");
    expect(globalCss).toContain("border-top: 0;");
    expect(globalCss).toContain("border-radius: 0 0 var(--feature-page-card-radius) var(--feature-page-card-radius);");
    expect(globalCss).toContain("padding: var(--feature-page-card-padding);");
    expect(globalCss).toContain(".page-shell__content > .surface-card {");
    expect(globalCss).toContain(".page-shell__content > .surface-card + .surface-card {");
    expect(globalCss).toContain(".page-shell__content .grid-auto,");
    expect(globalCss).toContain(".page-shell__content .info-card,");
    expect(globalCss).not.toContain(".page-shell__content .grid-auto > * + *");
    expect(globalCss).toContain(".page-shell--title-in-content {");
    expect(globalCss).toContain("grid-template-rows: minmax(0, 1fr);");
    expect(globalCss).toContain(".page-shell--title-in-content .page-shell__content {");
    expect(globalCss).toContain("border-radius: var(--feature-page-card-radius);");
    expect(globalCss).toContain(".board-workspace__list,");
    expect(globalCss).toContain("border-left: var(--two-column-content-divider);");
    expect(globalCss).toContain("grid-template-columns: var(--two-column-content-sidebar-width) minmax(0, 1fr);");
    expect(globalCss).toContain("align-items: stretch;");
    expect(globalCss).toContain("min-height: 100%;");
    expect(globalCss).toContain("padding: 0 var(--two-column-content-column-padding-inline);");
    expect(globalCss).toContain("gap: var(--two-column-content-title-gap);");
    expect(globalCss).toContain("gap: var(--two-column-content-list-gap);");
    expect(globalCss).toContain(".page-shell__headline h1 {");
    expect(globalCss).toContain("font-size: var(--font-size-page-title);");
    expect(globalCss).toContain("font-weight: var(--font-weight-page-title);");
    expect(globalCss).toContain(".surface-card__header h2,");
    expect(globalCss).toContain(".board-section-title h2,");
    expect(globalCss).toContain(".board-detail-preview h2 {");
    expect(globalCss).toContain("font-size: var(--font-size-content-title);");
    expect(globalCss).toContain("font-weight: var(--font-weight-content-title);");
    expect(globalCss).toContain("letter-spacing: var(--letter-spacing-feature-title);");
    expect(globalCss).toContain(".page-shell__content .pill {");
    expect(globalCss).toContain("display: none;");
    expect(globalCss).toContain("padding: var(--feature-page-title-offset-block) var(--feature-page-title-offset-inline);");
  });

  it("removes ad-hoc centered feature page shells from fallback routes", () => {
    const SectionPage = buildSectionPage("테스트 섹션", "테스트 설명");
    const forbiddenHtml = renderToStaticMarkup(<ForbiddenPage />);
    const sectionHtml = renderToStaticMarkup(<SectionPage />);

    expect(forbiddenHtml).toContain('class="page-shell"');
    expect(sectionHtml).toContain('class="page-shell"');
    expect(sectionHtml).not.toContain('class="page-shell__title-link"');
    expect(forbiddenHtml).not.toContain("max-width:720px");
    expect(sectionHtml).not.toContain("max-width:860px");
    expect(forbiddenHtml).not.toContain("padding:48px 24px");
    expect(sectionHtml).not.toContain("padding:48px 24px");
  });
});
