import React from "react";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import ForbiddenPage from "./app/forbidden/page";
import { buildSectionPage } from "./app/section-page";

describe("feature page content spacing baseline", () => {
  it("keeps desktop feature pages on the shared PageShell spacing model", () => {
    const globalCss = readFileSync(new URL("./app/globals.css", import.meta.url), "utf8");

    expect(globalCss).toContain("--desktop-sidebar-collapsed-width: 86px");
    expect(globalCss).toContain("--app-shell-max-width: 1120px;");
    expect(globalCss).toContain("--app-shell-viewport-gutter: 24px;");
    expect(globalCss).toContain("--app-topbar-bg: rgba(248, 250, 252, 0.92);");
    expect(globalCss).toContain("--app-topbar-border: 1px solid rgba(219, 226, 234, 0.9);");
    expect(globalCss).toContain("--app-topbar-min-height: 64px;");
    expect(globalCss).toContain("--app-body-padding-top: var(--space-xl);");
    expect(globalCss).toContain("--app-body-mobile-bottom-extra: 28px;");
    expect(globalCss).toContain("--desktop-sidebar-link-bg: rgba(255, 255, 255, 0.72);");
    expect(globalCss).toContain("--desktop-sidebar-link-transition: background-color 160ms ease, color 160ms ease;");
    expect(globalCss).toContain("--page-shell-gap: var(--space-xl);");
    expect(globalCss).toContain("--hero-card-text-color: var(--surface-subtle);");
    expect(globalCss).toContain("--desktop-content-padding-inline: clamp(6px, 0.72vw, 12px)");
    expect(globalCss).toContain("--feature-page-outer-gap-block: var(--desktop-content-padding-inline);");
    expect(globalCss).toContain("--feature-page-outer-gap-inline: var(--desktop-content-padding-inline);");
    expect(globalCss).toContain("--feature-page-card-radius: 18px;");
    expect(globalCss).toContain("--feature-page-card-padding: 14px;");
    expect(globalCss).toContain("--feature-page-title-offset-block: var(--feature-page-card-padding);");
    expect(globalCss).toContain("--feature-page-title-offset-inline: var(--feature-page-card-padding);");
    expect(globalCss).toContain("--feature-page-title-content-gap: 0px;");
    expect(globalCss).toContain("--feature-page-shell-height: calc(var(--app-shell-main-height) - var(--feature-page-outer-gap-block) - var(--feature-page-outer-gap-block));");
    expect(globalCss).toContain("--feature-page-shell-overflow: hidden;");
    expect(globalCss).toContain("--feature-page-content-max-height: 100%;");
    expect(globalCss).toContain("--two-column-content-height: 100%;");
    expect(globalCss).toContain("--two-column-content-overflow: hidden;");
    expect(globalCss).toContain("--two-column-content-column-max-height: 100%;");
    expect(globalCss).toContain("--two-column-content-column-overflow-y: auto;");
    expect(globalCss).toContain("--desktop-sidebar-max-height: var(--desktop-sidebar-height);");
    expect(globalCss).toContain("--desktop-sidebar-nav-max-height: 100%;");
    expect(globalCss).toContain("--two-column-content-sidebar-width: minmax(220px, 260px);");
    expect(globalCss).toContain("--two-column-content-sidebar-width-compact: minmax(200px, 240px);");
    expect(globalCss).toContain("--two-column-content-column-padding-inline: clamp(16px, 1.6vw, 22px);");
    expect(globalCss).toContain("--two-column-content-column-gap: 0px;");
    expect(globalCss).toContain("--two-column-content-title-gap: 14px;");
    expect(globalCss).toContain("--two-column-content-list-gap: 18px;");
    expect(globalCss).toContain("--two-column-content-divider: 1px solid var(--line);");
    expect(globalCss).toContain("--board-home-feed-gap: 14px;");
    expect(globalCss).toContain("--board-home-tab-group-gap: 6px;");
    expect(globalCss).toContain("--board-home-tab-group-padding: 4px;");
    expect(globalCss).toContain("--board-home-tab-group-border: 1px solid var(--primary-soft-strong);");
    expect(globalCss).toContain("--board-home-tab-group-bg: var(--surface-subtle);");
    expect(globalCss).toContain("--board-home-tab-min-width: 76px;");
    expect(globalCss).toContain("--board-home-tab-padding-block: var(--space-sm);");
    expect(globalCss).toContain("--board-home-tab-padding-inline: 14px;");
    expect(globalCss).toContain("--board-home-tab-active-bg: var(--primary-hover);");
    expect(globalCss).toContain("--board-home-tab-active-text: var(--surface);");
    expect(globalCss).toContain("--board-home-tab-focus-outline: 2px solid rgba(37, 99, 235, 0.28);");
    expect(globalCss).toContain("--board-home-tab-focus-outline-offset: 3px;");
    expect(globalCss).toContain("--board-post-row-gap: var(--space-md);");
    expect(globalCss).toContain("--board-post-row-padding-block: 14px;");
    expect(globalCss).toContain("--board-home-feed-row-gap: 7px;");
    expect(globalCss).toContain("--board-home-feed-row-padding-block: 18px;");
    expect(globalCss).toContain("--board-home-feed-row-divider: 1px solid var(--line);");
    expect(globalCss).toContain("--board-post-meta-gap: var(--space-sm);");
    expect(globalCss).toContain("--board-post-avatar-size: 24px;");
    expect(globalCss).toContain("--board-post-avatar-bg: var(--primary-soft-strong);");
    expect(globalCss).toContain("--board-post-arrow-color: #94a3b8;");
    expect(globalCss).toContain(".page-shell,");
    expect(globalCss).toContain("--page-shell-width: min(var(--app-shell-max-width), calc(100vw - var(--app-shell-viewport-gutter)));");
    expect(globalCss).toContain("width: var(--page-shell-width);");
    expect(globalCss).toContain("background: var(--app-topbar-bg);");
    expect(globalCss).toContain("border-bottom: var(--app-topbar-border);");
    expect(globalCss).toContain("min-height: var(--app-topbar-min-height);");
    expect(globalCss).toContain("--app-shell-body-padding: var(--app-body-padding-top) 0 calc(var(--mobile-bottom-nav-offset) + var(--mobile-bottom-nav-height) + env(safe-area-inset-bottom, 0px) + var(--app-body-mobile-bottom-extra));");
    expect(globalCss).toContain("padding: var(--app-shell-body-padding);");
    expect(globalCss).toContain("height: var(--desktop-sidebar-height);");
    expect(globalCss).toContain("max-height: var(--desktop-sidebar-max-height);");
    expect(globalCss).toContain("max-height: var(--desktop-sidebar-nav-max-height);");
    expect(globalCss).toContain("background: var(--desktop-sidebar-link-bg);");
    expect(globalCss).toContain("transition: var(--desktop-sidebar-link-transition);");
    expect(globalCss).toContain("gap: var(--page-shell-gap);");
    expect(globalCss).toContain("color: var(--hero-card-text-color);");
    expect(globalCss).toContain("width: 100%");
    expect(globalCss).toContain("max-width: none");
    expect(globalCss).toContain("padding-inline: var(--feature-page-outer-gap-inline)");
    expect(globalCss).toContain("--desktop-status-banner-width: calc(100% - var(--desktop-content-padding-inline) - var(--desktop-content-padding-inline));");
    expect(globalCss).toContain("width: var(--desktop-status-banner-width);");
    expect(globalCss).toContain(".page-shell__content {");
    expect(globalCss).toContain("gap: 0;");
    expect(globalCss).toContain("background: var(--surface);");
    expect(globalCss).toContain("grid-template-rows: auto minmax(0, 1fr);");
    expect(globalCss).toContain("height: var(--feature-page-shell-height);");
    expect(globalCss).toContain("overflow: var(--feature-page-shell-overflow);");
    expect(globalCss).toContain(".app-shell__body > .page-shell {");
    expect(globalCss).toContain("flex: 1 1 auto;");
    expect(globalCss).toContain("max-height: var(--feature-page-shell-height);");
    expect(globalCss).toContain("padding-top: var(--feature-page-outer-gap-block);");
    expect(globalCss).toContain("padding-bottom: var(--feature-page-outer-gap-block);");
    expect(globalCss).not.toContain("padding-bottom: 28px;");
    expect(globalCss).toContain("overflow: hidden;");
    expect(globalCss).toContain("overflow-y: auto;");
    expect(globalCss).toContain(".page-shell__content:hover");
    expect(globalCss).toContain("padding: var(--feature-page-title-offset-block) var(--feature-page-title-offset-inline);");
    expect(globalCss).toContain("border-radius: var(--feature-page-card-radius) var(--feature-page-card-radius) 0 0;");
    expect(globalCss).toContain("border-top: 0;");
    expect(globalCss).toContain("border-radius: 0 0 var(--feature-page-card-radius) var(--feature-page-card-radius);");
    expect(globalCss).toContain("max-height: var(--feature-page-content-max-height);");
    expect(globalCss).toContain("padding: var(--feature-page-card-padding);");
    expect(globalCss).toContain(".page-shell__content > .surface-card {");
    expect(globalCss).toContain(".page-shell__content > .surface-card + .surface-card {");
    expect(globalCss).toContain(".page-shell__content .grid-auto,");
    expect(globalCss).toContain(".page-shell__content .info-card,");
    expect(globalCss).not.toContain(".page-shell__content .grid-auto > * + *");
    expect(globalCss).toContain(".page-shell--title-in-content {");
    expect(globalCss).toContain("grid-template-rows: minmax(0, 1fr);");
    expect(globalCss).toContain(".page-shell--title-in-content .page-shell__content {");
    expect(globalCss).toContain("border-radius: var(--feature-page-card-radius);");
    expect(globalCss).toContain(".board-workspace__list,");
    expect(globalCss).toContain("border-left: var(--two-column-content-divider);");
    expect(globalCss).toContain("grid-template-columns: var(--two-column-content-sidebar-width) minmax(0, 1fr);");
    expect(globalCss).toContain("align-items: stretch;");
    expect(globalCss).toContain("height: var(--two-column-content-height);");
    expect(globalCss).toContain("min-height: 100%;");
    expect(globalCss).toContain("overflow: var(--two-column-content-overflow);");
    expect(globalCss).toContain("max-height: var(--two-column-content-column-max-height);");
    expect(globalCss).toContain("overflow-y: var(--two-column-content-column-overflow-y);");
    expect(globalCss).toContain("padding: 0 var(--two-column-content-column-padding-inline);");
    expect(globalCss).toContain("gap: var(--two-column-content-title-gap);");
    expect(globalCss).toContain("gap: var(--two-column-content-list-gap);");
    expect(globalCss).toContain(".board-home-feed {");
    expect(globalCss).toContain("gap: var(--board-home-feed-gap);");
    expect(globalCss).toContain(".board-home-tabs {");
    expect(globalCss).toContain("gap: var(--board-home-tab-group-gap);");
    expect(globalCss).toContain("padding: var(--board-home-tab-group-padding);");
    expect(globalCss).toContain("border: var(--board-home-tab-group-border);");
    expect(globalCss).toContain("background: var(--board-home-tab-group-bg);");
    expect(globalCss).toContain("min-width: var(--board-home-tab-min-width);");
    expect(globalCss).toContain("padding: var(--board-home-tab-padding-block) var(--board-home-tab-padding-inline);");
    expect(globalCss).toContain("background: var(--board-home-tab-active-bg);");
    expect(globalCss).toContain("color: var(--board-home-tab-active-text);");
    expect(globalCss).toContain("outline: var(--board-home-tab-focus-outline);");
    expect(globalCss).toContain("outline-offset: var(--board-home-tab-focus-outline-offset);");
    expect(globalCss).toContain("gap: var(--board-post-row-gap);");
    expect(globalCss).toContain("padding: var(--board-post-row-padding-block) 0;");
    expect(globalCss).toContain("gap: var(--board-home-feed-row-gap);");
    expect(globalCss).toContain("padding: var(--board-home-feed-row-padding-block) 0;");
    expect(globalCss).toContain("border-top: var(--board-home-feed-row-divider);");
    expect(globalCss).toContain("gap: var(--board-post-meta-gap);");
    expect(globalCss).toContain("width: var(--board-post-avatar-size);");
    expect(globalCss).toContain("height: var(--board-post-avatar-size);");
    expect(globalCss).toContain("background: var(--board-post-avatar-bg);");
    expect(globalCss).toContain("color: var(--board-post-arrow-color);");
    expect(globalCss).toContain(".page-shell__headline h1 {");
    expect(globalCss).toContain("font-size: var(--font-size-page-title);");
    expect(globalCss).toContain("font-weight: var(--font-weight-page-title);");
    expect(globalCss).toContain(".surface-card__header h2,");
    expect(globalCss).toContain(".board-section-title h2,");
    expect(globalCss).toContain(".board-detail-preview h2 {");
    expect(globalCss).toContain("font-size: var(--font-size-content-title);");
    expect(globalCss).toContain("font-weight: var(--font-weight-content-title);");
    expect(globalCss).toContain("letter-spacing: var(--letter-spacing-feature-title);");
    expect(globalCss).toContain(".page-shell__content .pill {");
    expect(globalCss).toContain("display: none;");
    expect(globalCss).toContain("padding: var(--feature-page-title-offset-block) var(--feature-page-title-offset-inline);");
  });

  it("removes ad-hoc centered feature page shells from fallback routes", () => {
    const SectionPage = buildSectionPage("테스트 섹션", "테스트 설명");
    const forbiddenHtml = renderToStaticMarkup(<ForbiddenPage />);
    const sectionHtml = renderToStaticMarkup(<SectionPage />);

    expect(forbiddenHtml).toContain('class="page-shell"');
    expect(sectionHtml).toContain('class="page-shell"');
    expect(sectionHtml).not.toContain('class="page-shell__title-link"');
    expect(forbiddenHtml).not.toContain("max-width:720px");
    expect(sectionHtml).not.toContain("max-width:860px");
    expect(forbiddenHtml).not.toContain("padding:48px 24px");
    expect(sectionHtml).not.toContain("padding:48px 24px");
  });
});
