import React from "react";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import MessengerPage from "./app/messenger/page";

describe("messenger preview page", () => {
  it("renders the board-like content title with conversation list and chat room columns plus a hidden new-message org popup", () => {
    const globalCss = readFileSync(new URL("./app/globals.css", import.meta.url), "utf8");
    const pageSource = readFileSync(new URL("./app/messenger/page.tsx", import.meta.url), "utf8");
    const html = renderToStaticMarkup(<MessengerPage />);

    expect(html).toContain("메신저");
    expect(html).toContain("대화목록");
    expect(html).toContain("채팅방");
    expect(html).toContain("새 메시지");
    expect(html).toContain('aria-label="메신저 더보기 메뉴 열기"');
    expect(html).toContain("가이드");
    expect(html).toContain("통합설정");
    expect(html).toContain("이름, 부서, 메시지 검색");
    expect(html).toContain("채팅방 선택 안내");
    expect(html).toContain("채팅방을 선택하세요");
    expect(html).toContain("왼쪽 대화목록에서 대화를 선택하면 내용이 표시됩니다.");
    expect(html).toContain("새 메시지 대상 선택 팝업");
    expect(html).toContain("새 메시지 받을 사람 검색");
    expect(html).toContain("조직도");
    expect(html).toContain("선택한 사람");
    expect(html).toContain("대화 시작");
    expect(html).toContain("새 메시지 팝업 닫기");
    expect(html).toContain("aria-expanded=\"true\"");
    expect(html).not.toContain("메시지 입력 preview");
    expect(html).not.toContain("메시지 목록 preview");
    expect(html).not.toContain("첨부 메뉴 열기");
    expect(html).not.toContain("메시지 보내기");
    expect(html).not.toContain("채팅방 닫기");
    expect(pageSource).toContain("closeActiveThread");
    expect(pageSource).toContain("handleLeaveActiveThread");
    expect(pageSource).toContain("appRoutes.messenger.leaveThread");
    expect(pageSource).toContain("messengerThreadLeaveResponseSchema");
    expect(pageSource).toContain("handleComposerKeyDown");
    expect(pageSource).toContain('event.key !== "Enter" || event.shiftKey');
    expect(pageSource).toContain("채팅방 메뉴 열기");
    expect(pageSource).toContain("채팅방 메뉴");
    expect(pageSource).toContain("설정");
    expect(pageSource).toContain("나가기");
    expect(pageSource).toContain("채팅방 닫기");
    expect(pageSource).toContain("첨부 메뉴 열기");
    expect(pageSource).toContain("메시지 입력 도구 묶음");
    expect(pageSource).toContain("내 PC 파일첨부");
    expect(pageSource).toContain("문서함에서 선택");
    expect(pageSource).toContain("문서함에서 선택 팝업");
    expect(pageSource).toContain("문서함 선택 팝업 닫기");
    expect(pageSource).toContain("문서함 선택 목록");
    expect(pageSource).toContain("문서함 분류");
    expect(pageSource).toContain("공지/규정");
    expect(pageSource).toContain("인사/근태");
    expect(pageSource).toContain("업무자료");
    expect(pageSource).toContain("양식");
    expect(pageSource).toContain("전사 공지문.docx");
    expect(pageSource).toContain("회의자료.pdf");
    expect(pageSource).toContain("근태현황.xlsx");
    expect(pageSource).toContain("이모티콘 선택");
    expect(pageSource).toContain("이모티콘 선택 메뉴");
    expect(pageSource).toContain("이모티콘 분류");
    expect(pageSource).toContain("이모티콘 목록");
    expect(pageSource).toContain("표정");
    expect(pageSource).toContain("반응");
    expect(pageSource).toContain("업무");
    expect(pageSource).toContain("상태");
    expect(pageSource).toContain("기념");
    expect(pageSource).toContain("😀");
    expect(pageSource).toContain("📌");
    expect(pageSource).toContain("이모티콘 입력");
    expect(pageSource).toContain("메시지 보내기");
    expect(html).toContain("messenger-surface");
    expect(html).toContain("messenger-surface__title-button");
    expect(html).not.toContain("이번 preview 범위");
    expect(html).not.toContain("WebSocket 실시간 채팅");
    expect(html).not.toContain("운영 DB 실데이터 저장");
    expect(html).not.toContain(">대상 선택<");
    expect(html).not.toContain(">사람 검색<");
    expect(html).not.toContain(">닫기<");
    expect(html).not.toContain(">사진보내기<");

    expect(globalCss).toContain(".messenger-shell");
    expect(globalCss).toContain("--messenger-surface-height: 100%;");
    expect(globalCss).toContain("--messenger-shell-min-height: 0px;");
    expect(globalCss).toContain(".messenger-surface");
    expect(globalCss).toContain("grid-template-rows: minmax(0, 1fr);");
    expect(globalCss).toContain(".messenger-sidebar__header h1");
    expect(globalCss).toContain(".messenger-empty-state");
    expect(globalCss).toContain("grid-template-columns: minmax(280px, 340px) minmax(0, 1fr);");
    expect(globalCss).toContain("height: var(--messenger-surface-height);");
    expect(globalCss).toContain("overflow-y: var(--messenger-thread-list-overflow-y);");
    expect(globalCss).toContain("overflow-y: var(--messenger-message-list-overflow-y);");
    expect(globalCss).toContain(".messenger-recipient-backdrop[hidden]");
    expect(globalCss).toContain(".messenger-document-backdrop[hidden]");
    expect(globalCss).toContain(".messenger-recipient-backdrop .messenger-recipient-panel");
    expect(globalCss).toContain(".messenger-document-panel");
    expect(globalCss).toContain(".messenger-dialog-close");
    expect(globalCss).toContain(".messenger-conversation-close");
    expect(globalCss).toContain(".messenger-conversation-actions");
    expect(globalCss).toContain(".messenger-conversation-menu");
    expect(globalCss).toContain(".messenger-conversation-menu__leave");
    expect(globalCss).toContain(".messenger-org-group__toggle");
    expect(globalCss).toContain(".messenger-org-group__contacts[hidden]");
    expect(globalCss).toContain(".messenger-thread[aria-current=\"page\"]");
    expect(globalCss).toContain(".messenger-message--mine");
    expect(globalCss).toContain("grid-template-columns: minmax(0, 1fr) max-content;");
    expect(globalCss).toContain(".messenger-composer-input-box");
    expect(globalCss).toContain("grid-template-columns: 42px minmax(0, 1fr) 42px;");
    expect(globalCss).toContain(".messenger-composer-input-box > * + *");
    expect(globalCss).toContain("border-left: 0;");
    expect(globalCss).toContain(".messenger-composer-input-box .messenger-composer-input");
    expect(globalCss).toContain("resize: none;");
    expect(globalCss).toContain("max-height: 96px;");
    expect(globalCss).toContain(".messenger-file-input");
    expect(globalCss).toContain(".messenger-attachment-preview");
    expect(pageSource).toContain("FeatureFileAttachmentBox");
    expect(globalCss).toContain(".feature-file-box__header");
    expect(globalCss).toContain(".messenger-composer-icon-button");
    expect(globalCss).toContain("border-radius: var(--radius-pill);");
    expect(globalCss).toContain(".messenger-send-button svg");
    expect(globalCss).toContain(".messenger-surface__title-button");
    expect(globalCss).toContain(".messenger-popover-menu[hidden]");
    expect(globalCss).toContain(".messenger-attachment-menu[hidden]");
    expect(globalCss).toContain(".messenger-emoji-menu[hidden]");
    expect(globalCss).toContain(".messenger-popover-menu button");
    expect(globalCss).toContain(".messenger-emoji-tabs");
    expect(globalCss).toContain(".messenger-emoji-grid");
    expect(globalCss).toContain(".messenger-document-tabs");
    expect(globalCss).toContain("aria-pressed=\"true\"");
    expect(globalCss).toContain(".messenger-document-list button");
    expect(globalCss).toContain("white-space: pre-line;");
    expect(globalCss).toContain("cursor: pointer;");
  });
});
