import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import EmployeesPage from "./app/employees/page";
import ManagementSupportHrPage from "./app/management-support/hr/page";
import MePage from "./app/me/page";
import OrgPage from "./app/org/page";

describe("org/employees/admin boundaries", () => {
  it("keeps employees page focused on general lookup instead of admin actions", () => {
    const html = renderToStaticMarkup(<EmployeesPage />);

    expect(html).toContain("직원");
    expect(html).toContain("직원 목록");
    expect(html).toContain("직원 상세");
    expect(html).toContain("근무 상태");
    expect(html).toContain("권한 요청");
    expect(html).not.toContain("초대 실행");
    expect(html).not.toContain("권한 저장");
    expect(html).not.toContain("COMPANY_ADMIN");
    expect(html).not.toContain("HR_ADMIN");
    expect(html).not.toContain("Phase");
  });

  it("keeps org page read-only and separates policy-sensitive access scope", () => {
    const html = renderToStaticMarkup(<OrgPage />);

    expect(html).toContain("조직도");
    expect(html).toContain("조직 트리");
    expect(html).toContain("부서 상세");
    expect(html).toContain("구성원");
    expect(html).toContain("접근 범위");
    expect(html).not.toContain("역할 생성");
    expect(html).not.toContain("권한 저장");
    expect(html).not.toContain("운영 DB seed");
  });

  it("keeps me page focused on personal workspace and read-only context", () => {
    const html = renderToStaticMarkup(<MePage />);

    expect(html).toContain("feature-workspace");
    expect(html).toContain("내 정보");
    expect(html).toContain("보안");
    expect(html).toContain("권한");
    expect(html).toContain("연결 업무");
    expect(html).toContain("/employees");
    expect(html).toContain("/payroll/me");
    expect(html).not.toContain("권한 저장");
    expect(html).not.toContain("초대 실행");
    expect(html).not.toContain("dev-safe");
  });

  it("keeps management support employee management list-first and opens creation in the right detail panel", async () => {
    const html = renderToStaticMarkup(await ManagementSupportHrPage());
    const clientSource = await import("node:fs/promises").then((fs) =>
      fs.readFile("app/management-support/_components/management-support-hr-client.tsx", "utf8"),
    );

    expect(html).toContain("사원정보관리");
    expect(html).toContain("aria-label=\"사원정보관리 현황 작업\"");
    expect(html).toContain("+ 사원 생성");
    expect(html).not.toContain(">등록<");
    expect(html).toContain("삭제");
    expect(html).toContain("aria-label=\"사원 목록\"");
    expect(html).toContain("feature-workspace__status-grid--employee-summary");
    expect(html).not.toContain("사내임직원 로그인 ID 또는 이메일");
    expect(html).not.toContain("사내임직원 초기 역할");
    expect(html).not.toContain("사내임직원 계정 생성");
    expect(clientSource).toContain("<ConfirmDialog");
    expect(clientSource).toContain("사원 생성을 닫을까요?");
    expect(clientSource).toContain("입력 중인 내용은 저장되지 않습니다.");
    expect(clientSource).toContain("requestCreatePanelClose");
    expect(clientSource).toContain("feature-workspace feature-workspace--hr");
    expect(clientSource).toContain("employee-create-form");
    expect(clientSource).toContain("이름*");
    expect(clientSource).toContain("주민등록번호*");
    expect(clientSource).toContain("연락처*");
    expect(clientSource).toContain("주소*");
    expect(clientSource).toContain("입사일자*");
    expect(clientSource).toContain("아이디*");
    expect(clientSource).toContain("비밀번호*");
    expect(clientSource).toContain("비밀번호 재입력*");
    expect(clientSource).toContain("사원 연락처");
    expect(clientSource).toContain("formatPhoneNumberInput");
    expect(clientSource).toContain("maxLength={13}");
    expect(clientSource).toContain("formatDateInput");
    expect(clientSource).toContain("expandedYearMatch");
    expect(clientSource).toContain("normalizeStrictDateInput");
    expect(clientSource).toContain("isStrictDateInput");
    expect(clientSource).toContain("strictDatePattern");
    expect(clientSource).toContain("max=\"9999-12-31\"");
    expect(clientSource).toContain("min=\"0001-01-01\"");
    expect(clientSource).toContain("pattern=\"\\d{4}-\\d{2}-\\d{2}\"");
    expect(clientSource).toContain("YYYY-MM-DD 형식의 연도 4자리 날짜");
    expect(clientSource).toContain("type=\"date\"");
    expect(clientSource).toContain("사원 외부이메일");
    expect(clientSource).toContain("contactPhone");
    expect(clientSource).toContain("externalEmail");
    expect(clientSource).toContain("필수 입력값을 확인해 주세요");
    expect(clientSource).toContain("주민등록번호 앞자리");
    expect(clientSource).toContain("주민등록번호 뒷자리");
    expect(clientSource).toContain("비밀번호 재입력");
    expect(clientSource).toContain("@{WEREHERE_EMAIL_DOMAIN}");
    expect(clientSource).toContain("employee-create-sensitive-field__toggle");
    expect(clientSource).toContain("SensitiveVisibilityIcon");
    expect(clientSource).toContain("EmployeeCreatePanelTab");
    expect(clientSource).toContain("employee-create-tabs");
    expect(clientSource).toContain("기본정보");
    expect(clientSource).toContain("계정정보");
    expect(clientSource).toContain("조직정보");
    expect(clientSource).toContain("activeCreatePanelTab === \"basic\"");
    expect(clientSource).toContain("activeCreatePanelTab === \"account\"");
    expect(clientSource).toContain("activeCreatePanelTab === \"organization\"");
    const createNameIndex = clientSource.indexOf("이름*");
    const createResidentIndex = clientSource.indexOf("주민등록번호*");
    const createAddressIndex = clientSource.indexOf("주소*");
    const createHireIndex = clientSource.indexOf("입사일자*");
    const createContactIndex = clientSource.indexOf("연락처*");
    const createRecognizedHireIndex = clientSource.indexOf("인정입사일자", createContactIndex);
    const createEmploymentCategoryIndex = clientSource.indexOf("채용구분");
    expect(createNameIndex).toBeLessThan(createResidentIndex);
    expect(createResidentIndex).toBeLessThan(createAddressIndex);
    expect(createAddressIndex).toBeLessThan(createHireIndex);
    expect(createHireIndex).toBeLessThan(createContactIndex);
    expect(createContactIndex).toBeLessThan(createRecognizedHireIndex);
    expect(createRecognizedHireIndex).toBeLessThan(createEmploymentCategoryIndex);
    expect(clientSource).toContain("employee-create-field-row employee-create-field-row--one");
    expect(clientSource).toContain("주소검색");
    expect(clientSource).toContain("우편번호 검색");
    expect(clientSource).toContain("사원 상세주소");
    expect(clientSource).toContain("검색된 결과가 없습니다.");
    expect(clientSource).toContain("addressSearchResponseSchema");
    expect(clientSource).toContain("handleAddressSearch");
    expect(clientSource).toContain("applyAddressSearchResult");
    expect(clientSource).toContain("appRoutes.admin.addressSearch");
    expect(clientSource).toContain("주소검색 결과 목록");
    expect(clientSource).toContain("addressSearchPageSize = 5");
    expect(clientSource).toContain("addressSearchMaxResults = 40");
    expect(clientSource).toContain("parsed.data.data.results.slice(0, addressSearchMaxResults)");
    expect(clientSource).toContain("pagedAddressSearchResults.map");
    expect(clientSource).toContain("addressSearchPageNumbers.map");
    expect(clientSource).toContain("setAddressSearchPage(pageNumber)");
    expect(clientSource).not.toContain("addressSearchResults.slice(0, 5).map");
    expect(clientSource).toContain("AddressDialogDraft");
    expect(clientSource).toContain("addressDialogDraft");
    expect(clientSource).toContain("openAddressSearchDialog");
    expect(clientSource).toContain("commitAddressDialogDraft");
    expect(clientSource).toContain("employee-create-address-field__search-control");
    expect(clientSource).toContain("aria-label=\"주소 검색 실행\"");
    expect(clientSource).toContain("employee-create-address-dialog__pagination");
    expect(clientSource).toContain("handleAddressDialogKeyDown");
    expect(clientSource).toContain("event.key === \"Escape\"");
    expect(clientSource).not.toContain("aria-label=\"주소검색 팝업\" onClick");
    expect(clientSource).not.toContain("event.stopPropagation()");
    expect(clientSource).toContain("주소검색 상세 주소");
    expect(clientSource).toContain("addressPostalCode");
    expect(clientSource).toContain("addressBase");
    expect(clientSource).toContain("addressDetail");
    expect(clientSource).toContain("loginLocalPart");
    expect(clientSource).toContain("WEREHERE_EMAIL_DOMAIN");
    expect(clientSource).toContain("appRoutes.admin.employeeReferenceMasters");
    expect(clientSource).toContain("adminUserReferenceMastersResponseSchema");
    expect(clientSource).toContain("employee-create-reference-picker");
    expect(clientSource).toContain("data-selection-mode=\"multiple\"");
    expect(clientSource).toContain("aria-label=\"사원 지사\"");
    expect(clientSource).toContain("aria-label=\"사원 부서\"");
    expect(clientSource).toContain("aria-label=\"사원 직급\"");
    expect(clientSource).toContain("aria-label=\"사원 직위\"");
    expect(clientSource).toContain("aria-label=\"사원 직책\"");
    expect(clientSource).not.toContain("employee-create-assignment-tabs");
    expect(clientSource).not.toContain("사원 기본 겸직 입력 그룹");
    expect(clientSource).not.toContain("handleAddConcurrentAssignment");
    expect(clientSource).not.toContain("concurrentAssignments");
    expect(clientSource).not.toContain("<select aria-label=\"사원 그룹 선택값\"");
    expect(clientSource).toContain("사용자그룹");
    expect(clientSource).toContain("employee-create-inline-picker");
    expect(clientSource).toContain("employee-create-inline-picker__item");
    expect(clientSource).toContain("jobGradeId: option.id");
    expect(clientSource).not.toContain("const defaultGroupOptions");
    expect(clientSource).not.toContain("const defaultDepartmentOptions");
    expect(clientSource).not.toContain("const defaultJobGradeOptions");
    expect(clientSource).toContain("계정상태");
    expect(clientSource).toContain("정상");
    expect(clientSource).toContain("중지");
    expect(clientSource).toContain("휴면");
    expect(clientSource).toContain("setIsCreatePanelOpen(true)");
    expect(clientSource).toContain("employee-detail-panel employee-detail-panel--create");
    expect(clientSource).toContain("employee-detail-panel__title");
    expect(clientSource).toContain("<strong className=\"employee-detail-panel__title\">사원 생성</strong>");
    expect(clientSource).toContain("employee-detail-panel__close");
    expect(clientSource).not.toContain("<strong>+ 사원 생성</strong>");
    expect(clientSource).toContain("<StandardButton intent=\"danger\" onClick={confirmCreatePanelClose} type=\"button\">닫기</StandardButton>");
    expect(clientSource).toContain("onClick={() => setActiveCreatePanelTab(\"account\")}");
    expect(clientSource).toContain("onClick={() => setActiveCreatePanelTab(\"organization\")}");
    expect(clientSource).toContain("activeCreatePanelTab === \"organization\" ? (");
    expect(clientSource).toContain("feature-workspace__plain-action");
    expect(clientSource).toContain("data-hr-input-size=\"short\"");
    expect(clientSource).toContain("data-hr-input-size=\"medium\"");
    expect(clientSource).toContain("data-hr-input-size=\"full\"");
    expect(clientSource).toContain("setIsDetailPanelOpen(false)");
    expect(clientSource).toContain("setIsDetailPanelOpen(true)");
    expect(clientSource).toContain("employeeDetailPanelTabs");
    expect(clientSource).toContain("@tanstack/react-table");
    expect(clientSource).toContain("useReactTable");
    expect(clientSource).toContain("getCoreRowModel");
    expect(clientSource).toContain("data-table-engine=\"tanstack\"");
    expect(clientSource).toContain("employeeTable.getHeaderGroups()");
    expect(clientSource).toContain("employeeTable.getRowModel().rows");
    expect(clientSource).not.toContain("{items.map((item) => (");
    expect(clientSource).toContain("기본정보");
    expect(clientSource).toContain("조직정보");
    expect(clientSource).toContain("계정·권한");
    expect(clientSource).toContain("보안");
    expect(clientSource).toContain("activeDetailPanelTab === \"profile\"");
    expect(clientSource).toContain("activeDetailPanelTab === \"organization\"");
    expect(clientSource).toContain("activeDetailPanelTab === \"account\"");
    expect(clientSource).toContain("activeDetailPanelTab === \"security\"");
    expect(clientSource).toContain("사원 기본정보 수정");
    const summaryStart = html.indexOf("aria-label=\"사원정보관리 현황\"");
    const wholeIndex = html.indexOf("전체", summaryStart);
    const activeIndex = html.indexOf("재직", summaryStart);
    const lockedIndex = html.indexOf("잠금", summaryStart);
    const dormantIndex = html.indexOf("휴면", summaryStart);
    const offboardedIndex = html.indexOf("퇴사", summaryStart);

    expect(summaryStart).toBeGreaterThanOrEqual(0);
    expect(wholeIndex).toBeLessThan(activeIndex);
    expect(activeIndex).toBeLessThan(lockedIndex);
    expect(lockedIndex).toBeLessThan(dormantIndex);
    expect(dormantIndex).toBeLessThan(offboardedIndex);
    expect(html).not.toContain("회원가입 신청");
    expect(html).not.toContain("회원가입 승인");
    expect(html).not.toContain("승인대기");
  });

  it("keeps employee management summary status cards on a five-column desktop grid", async () => {
    const globalCss = await import("node:fs/promises").then((fs) => fs.readFile("app/globals.css", "utf8"));

    expect(globalCss).toContain(".feature-workspace__status-grid--employee-summary");
    expect(globalCss).toContain("grid-template-columns: repeat(5, minmax(0, 1fr));");
  });

  it("styles employee detail as a right-side panel with top entrance motion", async () => {
    const globalCss = await import("node:fs/promises").then((fs) => fs.readFile("app/globals.css", "utf8"));

    expect(globalCss).toContain("--employee-detail-panel-width: 45vw;");
    expect(globalCss).toContain("--employee-detail-panel-top: var(--desktop-topbar-height, var(--app-topbar-min-height));");
    expect(globalCss).toContain("--desktop-sidebar-fixed-height: calc(100dvh - var(--desktop-topbar-height));");
    expect(globalCss).toContain(".feature-workspace__plain-action");
    expect(globalCss).toContain("padding: 0;");
    expect(globalCss).toContain(".feature-workspace__create-panel-grid");
    expect(globalCss).toContain(".employee-create-profile-card");
    expect(globalCss).toContain(".employee-create-field-row--two");
    expect(globalCss).toContain("grid-template-columns: var(--employee-create-left-column-width) max-content;");
    expect(globalCss).toContain("column-gap: var(--employee-create-two-column-gap);");
    expect(globalCss).toContain(".employee-create-field-row--two > label {");
    expect(globalCss).toContain("min-width: var(--hr-input-width-medium);");
    expect(globalCss).not.toContain(".employee-create-field-row--two > label {\n  width: fit-content;\n}");
    expect(globalCss).toContain(".employee-create-field-row--one");
    expect(globalCss).toContain(".employee-create-tabs");
    expect(globalCss).toContain(".employee-create-tabs__button");
    expect(globalCss).toContain(".employee-create-address-field");
    expect(globalCss).toContain(".employee-create-address-dialog");
    expect(globalCss).toContain(".employee-create-address-dialog__tabs");
    expect(globalCss).toContain(".employee-create-address-field__search-control");
    expect(globalCss).toContain(".employee-create-address-dialog__search-row");
    expect(globalCss).toContain(".employee-create-address-dialog__pagination");
    expect(globalCss).toContain("background: rgb(166 170 178 / 84%);");
    expect(globalCss).toContain("--employee-create-address-dialog-width: 720px;");
    expect(globalCss).toContain("--employee-create-address-dialog-height: 820px;");
    expect(globalCss).toContain("--employee-create-address-result-row-height: 72px;");
    expect(globalCss).toContain("grid-template-rows: auto auto minmax(0, 1fr) auto;");
    expect(globalCss).toContain("height: min(var(--employee-create-address-dialog-height), calc(100dvh - var(--space-2xl)));");
    expect(globalCss).toContain("grid-auto-rows: minmax(var(--employee-create-address-result-row-height), auto);");
    expect(globalCss).toContain("overflow-wrap: anywhere;");
    expect(globalCss).toContain("word-break: keep-all;");
    expect(globalCss).toContain("--employee-create-section-offset: var(--space-sm);");
    expect(globalCss).toContain("--employee-create-login-input-width: 140px;");
    expect(globalCss).toContain("padding-left: var(--employee-create-section-offset);");
    expect(globalCss).toContain("--employee-create-address-base-input-width: 400px;");
    expect(globalCss).toContain("--employee-create-address-detail-input-width: 260px;");
    expect(globalCss).toContain("--employee-create-left-column-width: var(--hr-input-width-medium);");
    expect(globalCss).toContain("--employee-create-two-column-gap: calc(var(--space-md) * 3);");
    expect(globalCss).toContain("grid-template-columns: auto minmax(0, var(--employee-create-address-base-input-width));");
    expect(globalCss).toContain("column-gap: 0;");
    expect(globalCss).toContain("row-gap: var(--space-xs);");
    expect(globalCss).toContain(".employee-create-address-field input[aria-label=\"사원 기본주소\"]");
    expect(globalCss).toContain("width: var(--employee-create-address-base-input-width);");
    expect(globalCss).toContain(".employee-create-address-field input[aria-label=\"사원 상세주소\"]");
    expect(globalCss).toContain("grid-column: 2;");
    expect(globalCss).toContain("width: var(--employee-create-address-detail-input-width);");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section .employee-create-address-field input[aria-label=\"사원 기본주소\"][data-hr-input-size=\"full\"]:not([type=\"checkbox\"])");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section .employee-create-address-field input[aria-label=\"사원 상세주소\"][data-hr-input-size=\"full\"]:not([type=\"checkbox\"])");
    expect(globalCss).toContain("justify-content: start;");
    expect(globalCss).toContain(".employee-create-email-field input[aria-label=\"사원 아이디\"]");
    expect(globalCss).toContain("grid-template-columns: minmax(0, var(--employee-create-login-input-width)) max-content;");
    expect(globalCss).toContain("justify-content: space-between;");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section [data-hr-input-size=\"short\"]");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section [data-hr-input-size=\"medium\"]");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section [data-hr-input-size=\"long\"]");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section [data-hr-input-size=\"full\"]");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section input[data-hr-input-size=\"short\"]:not([type=\"checkbox\"])");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form .employee-create-section input[data-hr-input-size=\"medium\"]:not([type=\"checkbox\"])");
    expect(globalCss).toContain("width: var(--hr-input-width-medium);");
    expect(globalCss).toContain(".employee-create-address-dialog__address-line input[aria-label=\"주소검색 상세 주소\"]:disabled");
    expect(globalCss).toContain(".employee-create-address-dialog__results");
    expect(globalCss).toContain(".employee-create-address-dialog__result");
    expect(globalCss).toContain(".employee-create-inline-picker");
    expect(globalCss).toContain(".employee-create-inline-picker__item");
    expect(globalCss).not.toContain(".employee-create-assignment-tabs");
    expect(globalCss).not.toContain(".employee-create-section-divider");
    expect(globalCss).toContain(".employee-create-email-field");
    expect(globalCss).toContain(".employee-create-resident-field");
    expect(globalCss).toContain("grid-template-columns: var(--hr-input-width-short) max-content var(--hr-input-width-short);");
    expect(globalCss).toContain(".employee-create-resident-field input[aria-label=\"주민등록번호 앞자리\"]");
    expect(globalCss).toContain(".employee-create-resident-field .employee-create-sensitive-field input[aria-label=\"주민등록번호 뒷자리\"]");
    expect(globalCss).toContain("width: var(--hr-input-width-short);");
    expect(globalCss).toContain(".employee-create-sensitive-field");
    expect(globalCss).toContain(".employee-create-sensitive-field:has(input[data-hr-input-size=\"medium\"])");
    expect(globalCss).toContain(".employee-create-inline-picker");
    expect(globalCss).toContain(".employee-create-sensitive-field__toggle");
    expect(globalCss).toContain(".employee-detail-panel__title");
    expect(globalCss).toContain("font-size: var(--feature-page-content-title-font-size);");
    expect(globalCss).toContain(".employee-detail-panel__close");
    expect(globalCss).toContain("font-size: 28px;");
    expect(globalCss).toContain(".employee-create-close-confirm__dialog");
    expect(globalCss).toContain("padding-right: 36px;");
    expect(globalCss).toContain("transform: translateY(-50%);");
    expect(globalCss).toContain("--hr-input-height: 36px;");
    expect(globalCss).toContain("--hr-input-filter-height: 32px;");
    expect(globalCss).toContain("--hr-input-border: 1px solid #e2e8f0;");
    expect(globalCss).toContain("--hr-input-radius: 6px;");
    expect(globalCss).toContain("--hr-input-padding: 4px 12px;");
    expect(globalCss).toContain("--hr-input-width-short: 160px;");
    expect(globalCss).toContain("--hr-input-width-medium: 260px;");
    expect(globalCss).toContain(".feature-workspace--hr .feature-workspace__form input:not([type=\"checkbox\"])");
    expect(globalCss).toContain("font: revert;");
    expect(globalCss).toContain("font-family: revert;");
    expect(globalCss).toContain("font-size: revert;");
    expect(globalCss).toContain("font-weight: revert;");
    expect(globalCss).toContain("[data-hr-input-size=\"short\"]");
    expect(globalCss).toContain("[data-hr-input-size=\"medium\"]");
    expect(globalCss).toContain("[data-hr-input-size=\"full\"]");
    expect(globalCss).toContain(".employee-detail-panel");
    expect(globalCss).toContain("--employee-detail-panel-fixed-height: calc(100dvh - var(--employee-detail-panel-top));");
    expect(globalCss).toContain("--employee-detail-panel-height: var(--employee-detail-panel-fixed-height);");
    expect(globalCss).toContain("--employee-detail-panel-divider: 1px solid var(--line-strong);");
    expect(globalCss).toContain("right: 0;");
    expect(globalCss).toContain("bottom: 0;");
    expect(globalCss).toContain("display: grid;");
    expect(globalCss).toContain("grid-template-rows: auto auto minmax(0, 1fr);");
    expect(globalCss).toContain("height: var(--employee-detail-panel-height);");
    expect(globalCss).toContain("max-height: var(--employee-detail-panel-height);");
    expect(globalCss).toContain("min-height: 0;");
    expect(globalCss).toContain("flex-shrink: 0;");
    expect(globalCss).toContain("border-left: var(--employee-detail-panel-divider);");
    expect(globalCss).toContain("border-radius: 0;");
    expect(globalCss).toContain("left: auto;");
    expect(globalCss).toContain("width: var(--employee-detail-panel-width);");
    expect(globalCss).toContain("height: 100%;");
    expect(globalCss).toContain("max-height: 100%;");
    expect(globalCss).toContain("align-content: start;");
    expect(globalCss).toContain("animation: employee-detail-panel-enter");
    expect(globalCss).toContain(".employee-detail-panel__tabs");
    expect(globalCss).toContain("grid-template-columns: repeat(4, minmax(0, 1fr));");
    expect(globalCss).toContain("--employee-detail-panel-tab-padding");
    expect(globalCss).toContain(".employee-detail-panel__tab[aria-selected=\"true\"]");
    expect(globalCss).toContain("@keyframes employee-detail-panel-enter");
    expect(globalCss).toContain("transform: translateY(var(--employee-detail-panel-translate-y));");
  });
});
