import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import UatPage from "./app/uat/page";
import { phase59RoleMatrixCards } from "./app/uat/phase59-uat-config";
import { roleScenarioCards } from "./app/uat/uat-package-config";

describe("Phase 60 internal release rehearsal package", () => {
  it("renders access info, role scenarios, issue template, facilitator guide, and approval gates in one page", () => {
    const html = renderToStaticMarkup(<UatPage />);
    const auditorScenario = roleScenarioCards.find((card) => card.role === "감사 담당자");
    const auditorMatrix = phase59RoleMatrixCards.find((card) => card.role === "AUDITOR");

    expect(auditorScenario).toBeDefined();
    expect(auditorScenario?.journey).toEqual(["/admin/audit-logs", "/documents", "/me"]);
    expect(auditorScenario?.actions).not.toContain("`/api/health` 는 최소 liveness 기준으로만 읽고 full monitoring 처럼 과장하지 않는다.");
    expect(auditorScenario?.happyPath).toContain("감사 후속 확인 route(`/documents` → `/me`)가 운영 관리자 점검 route 처럼 읽히지 않는다.");
    expect(auditorMatrix).toBeDefined();
    expect(auditorMatrix?.shouldSee).toBe("`/admin/audit-logs` read-only 추적, `/documents` 후속 문서 확인, `/me` 세션/권한 확인");

    expect(html).toContain("실사용 1차 내부 릴리즈 / UAT 패키지");
    expect(html).toContain("https://gw-web.wereheresp.workers.dev");
    expect(html).toContain("admin / 1234");
    expect(html).toContain("운영자/감사 담당자가 같은 live 환경");
    expect(html).toContain("Phase 60 빠른 entry");
    expect(html).toContain("관련 기능 가이드 링크");
    expect(html).toContain("게시판·공지 실사용 가이드");
    expect(html).toContain("참고 문서: <a href=");
    expect(html).toContain('href="https://github.com/wrhr-sp/gw/blob/main/docs/guides/phase-51-boards-live-operations-guide.md"');
    expect(html).toContain("역할별 시나리오 카드");
    expect(html).toContain("일반 직원");
    expect(html).toContain("승인자 / 팀장");
    expect(html).toContain("운영 관리자");
    expect(html).toContain("지점 관리자");
    expect(html).toContain("감사 담당자");
    expect(html).toContain("시나리오 A~F 묶음");
    expect(html).toContain("시나리오 A. 오늘 업무 시작하기");
    expect(html).toContain("시나리오 F. 상태/차단/복구 확인하기");
    expect(html).toContain("역할별 검증표");
    expect(html).toContain("보이면 안 되는 것");
    expect(html).toContain("사용자 도움말 / 관리자 안내 흐름");
    expect(html).toContain("운영 관리자 전용 안내 흐름");
    expect(html).toContain("팀장/지점 운영 확인 흐름");
    expect(html).toContain("이슈 분류 기준");
    expect(html).toContain("blocker");
    expect(html).toContain("approval-needed");
    expect(html).toContain("이슈 기록 템플릿");
    expect(html).toContain("진행자용 설명 순서");
    expect(html).toContain("참가자용 빠른 시작");
    expect(html).toContain("/documents → /me");
    expect(html).toContain("/dashboard → /management → /admin/users → /admin/policies → /payroll → /work-items/tax → /work-items/labor → /work-items/legal → /admin/audit-logs → /api/health");
    expect(html).toContain("/dashboard → /management → /payroll → /work-items/tax → /work-items/legal → /me");
    expect(html).toContain("/work-items/branch → /employees → /org → /management");
    expect(html).toContain("/admin/audit-logs → /documents → /me");
    expect(html).toContain("`/admin/audit-logs` read-only 추적, `/documents` 후속 문서 확인, `/me` 세션/권한 확인");
    expect(html).toContain("감사 후속 확인 route(`/documents` → `/me`)가 운영 관리자 점검 route 처럼 읽히지 않는다.");
    expect(html).not.toContain("최소 `/api/health` liveness");
    expect(html).not.toContain("감사 결과와 운영 최소 기준선(`/api/health`) 설명이 같은 관리자 묶음처럼 뭉개지지 않는다.");
    expect(html).toContain("인사 관리자 브리지 기준선");
    expect(html).toContain("운영 관리자 브리지 기준선");
    expect(html).toContain("/dashboard → /admin/users → /employees → /org → /me");
    expect(html).toContain("Phase 60 기능별 릴리즈 기준선");
    expect(html).toContain("직접 할 액션:");
    expect(html).toContain("happy path 결과:");
    expect(html).toContain("아직 dev-safe 인 부분:");
    expect(html).toContain("Phase 60 최종 검증 / 릴리즈 묶음");
    expect(html).toContain("live 직접 클릭 근거와 local preview/build/release gate 근거를 섞지 않고 분리해서 기록한다.");
    expect(html).toContain("최종 보고 체크리스트");
    expect(html).toContain("AI 챗봇 후보 안내");
    expect(html).toContain("실제 모델/API key/비용 발생/사내자료 검색/외부 전송은 별도 승인 전 실행하지 않습니다.");
    expect(html).toContain("release gate 성공, focused test/web build, rollback 확인 포인트");
    expect(html).toContain("실제 급여 지급, 은행 이체, 실세액 확정");
    expect(html).toContain("인사 관리자 브리지");
    expect(html).toContain("운영 관리자 브리지");
    expect(html).toContain("HR_ADMIN 은 계정관리 preview 와 조직 read model 을 먼저 확인하고, 허용되지 않은 `/management` 는 happy path 로 기록하지 않습니다.");
    expect(html).toContain("COMPANY_ADMIN 은 계정관리 preview 와 읽기 조회를 먼저 확인한 뒤에만 `/management` 운영 허브로 이어 갑니다.");
    expect(html.indexOf("접속 정보")).toBeLessThan(html.indexOf("Phase 60 빠른 entry"));
    expect(html.indexOf("Phase 60 빠른 entry")).toBeLessThan(html.indexOf("관련 기능 가이드 링크"));
    expect(html.indexOf("관련 기능 가이드 링크")).toBeLessThan(html.indexOf("역할별 시나리오 카드"));
    expect(html.indexOf("역할별 시나리오 카드")).toBeLessThan(html.indexOf("Phase 60 기능별 릴리즈 기준선"));
    expect(html.indexOf("Phase 60 기능별 릴리즈 기준선")).toBeLessThan(html.indexOf("이슈 분류 기준"));
    expect(html.indexOf("이슈 분류 기준")).toBeLessThan(html.indexOf("진행자용 설명 순서"));
  });
});
