import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("remaining balanced design tokens", () => {
  it("keeps form, data, empty-state, and mobile tokens on the existing-average B baseline", () => {
    const globalCss = readFileSync("app/globals.css", "utf8");

    expect(globalCss).toContain("--form-control-height: 40px;");
    expect(globalCss).toContain("--form-control-radius: var(--radius-md);");
    expect(globalCss).toContain("--form-control-padding: 12px 14px;");
    expect(globalCss).toContain("--form-textarea-min-height: 120px;");
    expect(globalCss).toContain("--form-grid-gap: var(--space-md);");
    expect(globalCss).toContain("--form-grid-min: 180px;");
    expect(globalCss).toContain("--state-disabled-opacity: 0.6;");
    expect(globalCss).toContain("--state-disabled-cursor: not-allowed;");
    expect(globalCss).toContain("--data-card-gap: 10px;");
    expect(globalCss).toContain("--status-badge-height: 22px;");
    expect(globalCss).toContain("--status-badge-min-width: 22px;");
    expect(globalCss).toContain("--status-badge-font-size: var(--font-size-badge-px);");
    expect(globalCss).toContain("--empty-state-gap: 10px;");
    expect(globalCss).toContain("--empty-state-action-gap: var(--space-xs);");
    expect(globalCss).toContain("--status-banner-padding: 14px var(--space-lg);");
    expect(globalCss).toContain("--status-banner-radius: var(--radius-lg);");
    expect(globalCss).toContain("--mobile-nav-height: 74px;");
    expect(globalCss).toContain("--mobile-nav-max-width: 640px;");
    expect(globalCss).toContain("--mobile-nav-collapsed-width: 56px;");
    expect(globalCss).toContain("--mobile-nav-toggle-width: 48px;");
    expect(globalCss).toContain("--mobile-nav-gap: 4px;");
    expect(globalCss).toContain("--mobile-touch-target: 48px;");
    expect(globalCss).toContain("--mobile-nav-edge-gutter: 12px;");
    expect(globalCss).toContain("--mobile-nav-viewport-gutter: 24px;");
    expect(globalCss).toContain("--mobile-nav-bg: linear-gradient(180deg, rgba(255, 255, 255, 0.42) 0%, rgba(219, 234, 254, 0.2) 100%), rgba(248, 250, 252, 0.78);");
    expect(globalCss).toContain("--mobile-nav-border: 1px solid rgba(255, 255, 255, 0.52);");
    expect(globalCss).toContain("--mobile-nav-toggle-bg: rgba(255, 255, 255, 0.46);");
    expect(globalCss).toContain("--mobile-nav-toggle-hover-bg: rgba(255, 255, 255, 0.72);");
    expect(globalCss).toContain("--mobile-nav-icon-wrap-size: 24px;");
    expect(globalCss).toContain("--mobile-nav-icon-size: 20px;");
    expect(globalCss).toContain("--mobile-nav-badge-size: 19px;");
    expect(globalCss).toContain("--mobile-nav-active-pill-bg: rgba(255, 255, 255, 0.5);");
    expect(globalCss).toContain("--mobile-nav-narrow-collapsed-width: 54px;");
    expect(globalCss).toContain("--mobile-nav-narrow-toggle-width: 46px;");

    expect(globalCss).toContain("padding: var(--status-banner-padding);");
    expect(globalCss).toContain("border-radius: var(--status-banner-radius);");
    expect(globalCss).toContain("gap: var(--data-card-gap);");
    expect(globalCss).toContain("min-height: var(--mobile-touch-target);");
    expect(globalCss).toContain("opacity: var(--state-disabled-opacity);");
    expect(globalCss).toContain("cursor: var(--state-disabled-cursor);");
    expect(globalCss).toContain("gap: var(--empty-state-action-gap);");
    expect(globalCss).toContain("font-size: var(--empty-state-copy-size);");
    expect(globalCss).toContain("gap: var(--empty-state-gap);");
    expect(globalCss).toContain("grid-template-columns: repeat(auto-fit, minmax(var(--form-grid-min), 1fr));");
    expect(globalCss).toContain("min-height: var(--form-control-height);");
    expect(globalCss).toContain("border-radius: var(--form-control-radius);");
    expect(globalCss).toContain("padding: var(--form-control-padding);");
    expect(globalCss).toContain("min-height: var(--form-textarea-min-height);");
    expect(globalCss).toContain("--bottom-nav-width: min(var(--mobile-nav-max-width), calc(100vw - var(--mobile-nav-viewport-gutter)));");
    expect(globalCss).toContain("width: var(--bottom-nav-width);");
    expect(globalCss).toContain("background: var(--mobile-nav-bg);");
    expect(globalCss).toContain("border: var(--mobile-nav-border);");
    expect(globalCss).toContain("width: var(--mobile-nav-collapsed-width);");
    expect(globalCss).toContain("width: var(--mobile-nav-toggle-width);");
    expect(globalCss).toContain("gap: var(--mobile-nav-gap);");
    expect(globalCss).toContain("padding: var(--mobile-nav-padding) var(--mobile-nav-padding) var(--mobile-nav-padding) 0;");
    expect(globalCss).toContain("min-height: var(--mobile-nav-link-min-height);");
    expect(globalCss).toContain("min-height: var(--mobile-nav-pill-min-height);");
    expect(globalCss).toContain("width: var(--mobile-nav-icon-wrap-size);");
    expect(globalCss).toContain("width: var(--mobile-nav-icon-size);");
    expect(globalCss).toContain("min-width: var(--mobile-nav-badge-size);");
    expect(globalCss).toContain("background: var(--mobile-nav-active-pill-bg);");
    expect(globalCss).toContain("width: var(--mobile-nav-narrow-collapsed-width);");
    expect(globalCss).toContain("width: var(--mobile-nav-narrow-toggle-width);");
    expect(globalCss).toContain("--status-badge-min-width: 22px;");
    expect(globalCss).toContain("--status-badge-height: 22px;");
  });
});
