import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("groupware typography baseline", () => {
  it("self-hosts Pretendard and routes all app text through typography tokens", () => {
    const globalCss = readFileSync("app/globals.css", "utf8");
    const tinymceContentCss = readFileSync("public/tinymce/skins/content/default/content.min.css", "utf8");
    const realUsagePanels = readFileSync("app/_components/real-usage-panels.tsx", "utf8");

    expect(existsSync("public/fonts/pretendard/PretendardVariable.woff2")).toBe(true);
    expect(existsSync("public/fonts/pretendard/LICENSE.txt")).toBe(true);
    expect(globalCss).toContain('font-family: "Pretendard Variable";');
    expect(globalCss).toContain('src: url("/fonts/pretendard/PretendardVariable.woff2") format("woff2-variations");');
    expect(globalCss).toContain('--font-family-sans: "Pretendard Variable", Pretendard');
    expect(globalCss).toContain("font-family: var(--font-family-sans);");
    expect(globalCss).toContain("--font-size-2xs: 0.65rem;");
    expect(globalCss).toContain("--font-size-xs: 0.72rem;");
    expect(globalCss).toContain("--font-size-sm: 0.8rem;");
    expect(globalCss).toContain("--font-size-md: 0.88rem;");
    expect(globalCss).toContain("--font-size-body: 1rem;");
    expect(globalCss).toContain("--font-size-lg: 1.15rem;");
    expect(globalCss).toContain("--font-size-page-title: 1.22rem;");
    expect(globalCss).toContain("--font-size-content-title: 1.15rem;");
    expect(globalCss).toContain("--font-size-feature-title: var(--font-size-page-title);");
    expect(globalCss).toContain("--font-size-xl: 1.42rem;");
    expect(globalCss).toContain("--font-weight-regular: 400;");
    expect(globalCss).toContain("--font-weight-medium: 500;");
    expect(globalCss).toContain("--font-weight-semibold: 600;");
    expect(globalCss).toContain("--font-weight-bold: 700;");
    expect(globalCss).toContain("--font-weight-heavy: 800;");
    expect(globalCss).toContain("--font-weight-black: 850;");
    expect(globalCss).toContain("--font-weight-page-title: var(--font-weight-bold);");
    expect(globalCss).toContain("--font-weight-content-title: var(--font-weight-bold);");
    expect(globalCss).toContain("--font-weight-feature-title: var(--font-weight-page-title);");
    expect(globalCss).toContain("--letter-spacing-feature-title: -0.04em;");
    expect(globalCss).toContain("--line-height-tight: 1;");
    expect(globalCss).toContain("--line-height-compact: 1.15;");
    expect(globalCss).toContain("--line-height-snug: 1.35;");
    expect(globalCss).toContain("--line-height-default: 1.45;");
    expect(globalCss).toContain("--line-height-readable: 1.55;");
    expect(globalCss).toContain("--line-height-comfortable: 1.65;");
    expect(globalCss).not.toContain("font-family: system-ui, sans-serif;");
    expect(globalCss).not.toContain("'Segoe UI',Roboto");
    expect(tinymceContentCss).toContain("Pretendard Variable");
    expect(tinymceContentCss).toContain("/fonts/pretendard/PretendardVariable.woff2");
    expect(realUsagePanels).toContain("font_family_formats: boardTinymceFontFamilyFormats");
    expect(realUsagePanels).toContain("elementpath: false");
    expect(realUsagePanels).toContain("content_style: boardTinymceContentStyle");
    expect(realUsagePanels).not.toContain("font-family: Arial, sans-serif");
    expect(realUsagePanels).toContain("기본 글꼴=Pretendard Variable,Pretendard,'Malgun Gothic','맑은 고딕',sans-serif");
    expect(realUsagePanels).toContain("프리텐다드=Pretendard Variable,Pretendard,sans-serif");
    expect(realUsagePanels).toContain("본고딕=Noto Sans KR,Noto Sans CJK KR,Source Han Sans KR,sans-serif");
    expect(realUsagePanels).toContain("수트=SUIT,sans-serif");
    expect(realUsagePanels).toContain("스포카 한 산스=Spoqa Han Sans Neo,Spoqa Han Sans,sans-serif");
    expect(realUsagePanels).toContain("나눔고딕=Nanum Gothic,NanumGothic,sans-serif");
    expect(realUsagePanels).toContain("나눔스퀘어=NanumSquare,Nanum Square,sans-serif");
    expect(realUsagePanels).toContain("맑은 고딕='Malgun Gothic','맑은 고딕',sans-serif");
    expect(realUsagePanels).toContain("맑은 고딕 Light='Malgun Gothic Semilight','맑은 고딕 Semilight','Malgun Gothic','맑은 고딕',sans-serif");
    expect(realUsagePanels).toContain("돋움=Dotum,'돋움',sans-serif");
    expect(realUsagePanels).toContain("돋움체=DotumChe,'돋움체',monospace");
    expect(realUsagePanels).toContain("굴림=Gulim,'굴림',sans-serif");
    expect(realUsagePanels).toContain("굴림체=GulimChe,'굴림체',monospace");
    expect(realUsagePanels).toContain("바탕=Batang,'바탕',serif");
    expect(realUsagePanels).toContain("바탕체=BatangChe,'바탕체',monospace");
    expect(realUsagePanels).toContain("궁서=Gungsuh,'궁서',serif");
    expect(realUsagePanels).toContain("궁서체=GungsuhChe,'궁서체',monospace");
    expect(realUsagePanels).toContain("Arial=Arial,Helvetica,sans-serif");
    expect(realUsagePanels).toContain("Calibri=Calibri,Arial,sans-serif");
    expect(realUsagePanels).toContain("Times New Roman=Times New Roman,Times,serif");
    expect(realUsagePanels).toContain("Inter=Inter,Arial,sans-serif");
    expect(realUsagePanels).toContain("Roboto=Roboto,Arial,sans-serif");
    expect(realUsagePanels).toContain("Open Sans=Open Sans,Arial,sans-serif");
    expect(realUsagePanels).toContain("IBM Plex Sans=IBM Plex Sans,Arial,sans-serif");
    expect(realUsagePanels).toContain("Fira Code=Fira Code,Courier New,monospace");
  });
});
