packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
patchedDependencies:
  asn1@0.2.6: patches/asn1@0.2.6.patch
  tr46@0.0.3: patches/tr46@0.0.3.patch
  whatwg-url@5.0.0: patches/whatwg-url@5.0.0.patch
  wrangler@4.98.0: patches/wrangler@4.98.0.patch
