"use client";

import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { appRoutes, erpAccountSubjectCreateRequestSchema, erpAccountSubjectListResponseSchema, erpAccountSubjectMutationResponseSchema, erpJournalEntryCreateRequestSchema, erpJournalEntryListResponseSchema, erpJournalEntryMutationResponseSchema, errorResponseSchema, type ErpAccountSubject, type ErpJournalEntry } from "@gw/shared";
import { FeaturePageOverflowMenu } from "../../../_components/feature-page-overflow-menu";
import { PageShell, Pill } from "../../../_components/page-shell";

type Toast = { tone: "accent" | "warning"; title: string; body: string } | null;
const amount = (value: number) => new Intl.NumberFormat("ko-KR").format(value);
async function readError(response: Response) { const payload = await response.json().catch(() => null); const parsed = errorResponseSchema.safeParse(payload); return parsed.success ? parsed.data.error.message : `${response.status} ${response.statusText}`; }
async function fetchAccounts(){ const r=await fetch(appRoutes.erp.accountSubjects,{credentials:"same-origin",cache:"no-store"}); if(!r.ok) throw new Error(await readError(r)); const p=erpAccountSubjectListResponseSchema.parse(await r.json()); return p.data.items; }
async function fetchEntries(){ const r=await fetch(appRoutes.erp.journalEntries,{credentials:"same-origin",cache:"no-store"}); if(!r.ok) throw new Error(await readError(r)); const p=erpJournalEntryListResponseSchema.parse(await r.json()); return p.data.items; }

export default function JournalsPage(){
  const [accounts,setAccounts]=useState<ErpAccountSubject[]>([]);
  const [entries,setEntries]=useState<ErpJournalEntry[]>([]);
  const [toast,setToast]=useState<Toast>(null);
  const [loading,setLoading]=useState(true);
  const [submitting,setSubmitting]=useState(false);
  const [accountForm,setAccountForm]=useState({code:"", name:"", type:"asset" as ErpAccountSubject["type"], memo:""});
  const [journalForm,setJournalForm]=useState({entryDate:new Date().toISOString().slice(0,10), title:"", debitAccountId:"", creditAccountId:"", amount:"", memo:""});
  const postedCount=useMemo(()=>entries.filter((entry)=>entry.status==="posted").length,[entries]);
  async function reload(){ setLoading(true); setToast(null); try { const [nextAccounts,nextEntries]=await Promise.all([fetchAccounts(),fetchEntries()]); setAccounts(nextAccounts); setEntries(nextEntries); setJournalForm((current)=>({ ...current, debitAccountId: current.debitAccountId || nextAccounts[0]?.id || "", creditAccountId: current.creditAccountId || nextAccounts[1]?.id || nextAccounts[0]?.id || "" })); } catch(error){ setToast({tone:"warning", title:"회계 정보를 불러오지 못했습니다.", body:error instanceof Error?error.message:"알 수 없는 오류입니다."}); } finally { setLoading(false); } }
  async function createAccount(event:FormEvent){ event.preventDefault(); setSubmitting(true); try { const payload=erpAccountSubjectCreateRequestSchema.parse({ code: accountForm.code, name: accountForm.name, type: accountForm.type, memo: accountForm.memo || undefined }); const r=await fetch(appRoutes.erp.accountSubjects,{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); if(!r.ok) throw new Error(await readError(r)); erpAccountSubjectMutationResponseSchema.parse(await r.json()); setAccountForm({code:"",name:"",type:"asset",memo:""}); await reload(); setToast({tone:"accent",title:"계정과목을 등록했습니다.",body:"저장 후 DB 목록을 다시 조회했습니다."}); } catch(error){ setToast({tone:"warning",title:"계정과목 등록 실패",body:error instanceof Error?error.message:"알 수 없는 오류입니다."}); } finally { setSubmitting(false); } }
  async function createJournal(event:FormEvent){ event.preventDefault(); setSubmitting(true); try { const value=Number(journalForm.amount); const payload=erpJournalEntryCreateRequestSchema.parse({ entryDate:journalForm.entryDate, title:journalForm.title, sourceType:"manual", memo:journalForm.memo || undefined, lines:[{accountSubjectId:journalForm.debitAccountId,debitAmount:value,creditAmount:0},{accountSubjectId:journalForm.creditAccountId,debitAmount:0,creditAmount:value}] }); const r=await fetch(appRoutes.erp.journalEntries,{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}); if(!r.ok) throw new Error(await readError(r)); erpJournalEntryMutationResponseSchema.parse(await r.json()); setJournalForm((current)=>({...current,title:"",amount:"",memo:""})); await reload(); setToast({tone:"accent",title:"전표를 등록했습니다.",body:"차변/대변 균형 검증 후 DB 목록을 다시 조회했습니다."}); } catch(error){ setToast({tone:"warning",title:"전표 등록 실패",body:error instanceof Error?error.message:"알 수 없는 오류입니다."}); } finally { setSubmitting(false); } }
  useEffect(()=>{ void reload(); },[]);
  return <PageShell title="회계 · 계정과목/전표/분개장" titlePlacement="content" titleHref={null}>
    <div className="feature-workspace" aria-label="계정과목 전표 분개장">
      <aside className="feature-workspace__nav" aria-label="회계 메뉴"><div className="feature-workspace__nav-header"><h1><button className="page-shell__title-link page-shell__title-button" onClick={()=>void reload()} type="button">전표/분개장</button></h1><FeaturePageOverflowMenu label="전표/분개장" /></div><div className="feature-workspace__tab-list" role="tablist" aria-label="회계 메뉴"><button aria-selected="true" className="feature-workspace__tab" role="tab" type="button"><span>전표</span><strong>{entries.length}</strong></button><button aria-selected="false" className="feature-workspace__tab" role="tab" type="button"><span>계정과목</span><strong>{accounts.length}</strong></button><a className="feature-workspace__tab" href="/management-support/erp/expenses"><span>지출결의</span><strong>이동</strong></a><a className="feature-workspace__tab" href="/management-support/erp/billings"><span>매출/청구</span><strong>이동</strong></a></div></aside>
      <section className="feature-workspace__panel" aria-labelledby="journals-heading"><div className="feature-workspace__panel-header"><div><h2 id="journals-heading">계정과목 / 전표 / 분개장</h2><p>자체 회계 처리를 위한 기초 계정과목과 차변/대변 전표를 내부 DB에 저장합니다.</p></div><p className="feature-workspace__permission-hint">외부 회계 서비스 호출 없이 기존 부서업무포털 권한을 따릅니다.</p></div>
      {toast ? <article className="info-card"><Pill tone={toast.tone}>확인</Pill><h3>{toast.title}</h3><p>{toast.body}</p></article> : null}
      <div className="feature-workspace__status-grid"><article className="feature-workspace__status feature-workspace__status--accent"><span>계정과목</span><strong>{accounts.length}개</strong><p>DB 조회 기준</p></article><article className="feature-workspace__status"><span>전표</span><strong>{entries.length}건</strong><p>차변/대변 균형</p></article><article className="feature-workspace__status feature-workspace__status--warning"><span>전기 완료</span><strong>{postedCount}건</strong><p>상태값 기준</p></article></div>
      <form className="feature-workspace__rows" onSubmit={createAccount} aria-label="계정과목 등록"><article className="feature-workspace__row"><div><strong>계정과목 등록</strong><span>전표에서 사용할 계정 코드를 등록합니다.</span><div className="form-grid form-grid--two"><label>코드<input value={accountForm.code} onChange={(e)=>setAccountForm((c)=>({...c,code:e.target.value}))} required /></label><label>이름<input value={accountForm.name} onChange={(e)=>setAccountForm((c)=>({...c,name:e.target.value}))} required /></label><label>유형<select value={accountForm.type} onChange={(e)=>setAccountForm((c)=>({...c,type:e.target.value as ErpAccountSubject["type"]}))}><option value="asset">자산</option><option value="liability">부채</option><option value="equity">자본</option><option value="revenue">수익</option><option value="expense">비용</option></select></label><label>메모<input value={accountForm.memo} onChange={(e)=>setAccountForm((c)=>({...c,memo:e.target.value}))} /></label></div></div><button className="feature-workspace__row-action" disabled={submitting} type="submit">등록</button></article></form>
      <form className="feature-workspace__rows" onSubmit={createJournal} aria-label="전표 등록"><article className="feature-workspace__row"><div><strong>전표 등록</strong><span>금액은 차변/대변 같은 금액으로 저장하며 불균형 전표는 API에서 차단합니다.</span><div className="form-grid form-grid--two"><label>일자<input type="date" value={journalForm.entryDate} onChange={(e)=>setJournalForm((c)=>({...c,entryDate:e.target.value}))} required /></label><label>제목<input value={journalForm.title} onChange={(e)=>setJournalForm((c)=>({...c,title:e.target.value}))} required /></label><label>차변 계정<select value={journalForm.debitAccountId} onChange={(e)=>setJournalForm((c)=>({...c,debitAccountId:e.target.value}))} required>{accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>대변 계정<select value={journalForm.creditAccountId} onChange={(e)=>setJournalForm((c)=>({...c,creditAccountId:e.target.value}))} required>{accounts.map((a)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select></label><label>금액<input min="1" type="number" value={journalForm.amount} onChange={(e)=>setJournalForm((c)=>({...c,amount:e.target.value}))} required /></label><label>메모<input value={journalForm.memo} onChange={(e)=>setJournalForm((c)=>({...c,memo:e.target.value}))} /></label></div></div><button className="feature-workspace__row-action" disabled={submitting || accounts.length < 2} type="submit">등록</button></article></form>
      <div className="feature-workspace__rows" aria-label="분개장 목록">{loading ? <article className="feature-workspace__row"><div><strong>불러오는 중</strong><span>계정과목과 전표를 조회하고 있습니다.</span></div><em>대기</em></article> : null}{entries.length===0&&!loading?<article className="feature-workspace__row"><div><strong>등록된 전표가 없습니다.</strong><span>계정과목 2개 이상을 먼저 등록한 뒤 전표를 만들 수 있습니다.</span></div><em>빈 상태</em></article>:null}{entries.map((entry)=><article className="feature-workspace__row" key={entry.id}><div><strong>{entry.title}</strong><span>{entry.entryNumber} · {entry.entryDate} · {entry.status}</span><p>차변 {amount(entry.totalDebitAmount)}원 · 대변 {amount(entry.totalCreditAmount)}원</p><p>{entry.lines.map((line)=>`${line.accountCode ?? ""} ${line.accountName ?? ""} ${line.debitAmount>0?"차변":"대변"} ${amount(line.debitAmount || line.creditAmount)}원`).join(" / ")}</p></div><em>{entry.status}</em></article>)}</div>
      </section>
    </div>
  </PageShell>;
}
