#!/usr/bin/env bash
export GW_BOT_HOME="${GW_BOT_HOME:-/home/wrhrgw/gw-dev-bot}"
export HERMES_HOME="${HERMES_HOME:-$GW_BOT_HOME/.hermes}"
export HERMES_BIN="${HERMES_BIN:-$GW_BOT_HOME/.hermes/hermes-agent/venv/bin/hermes}"
export HOME="$GW_BOT_HOME"
export XDG_CONFIG_HOME="$GW_BOT_HOME/.config"
export XDG_STATE_HOME="$GW_BOT_HOME/.local/state"
export XDG_CACHE_HOME="$GW_BOT_HOME/.cache"
export HERMES_KANBAN_BOARD="${HERMES_KANBAN_BOARD:-groupware}"
