import { describe, expect, it, vi } from "vitest";
import { createApp } from "../src/app";
import { createDailySalesService } from "../src/daily-sales/service";

const hotelId="50000000-0000-4000-8000-000000000001";
const salesId="da500000-0000-4000-8000-000000000001";
const categoryId="da510000-0000-4000-8000-000000000001";
const paymentMethodId="da520000-0000-4000-8000-000000000001";
const principal={companyId:"10000000-0000-0000-0000-000000000001",displayName:"매출 담당",identityId:"30000000-0000-4000-8000-000000000001",sessionId:"40000000-0000-4000-8000-000000000001",sessionToken:"opaque-daily-sales-token",userId:"20000000-0000-4000-8000-000000000001",userType:"INTERNAL_STAFF" as const};
const line={categoryId,paymentMethodId,grossAmount:200000,discountAmount:10000,refundAmount:5000,refundReason:"고객 요청 당일 환불"};
const publicSales={id:salesId,hotelId,businessDate:"2026-08-13",status:"LOCKED" as const,version:3,totals:{grossAmount:200000,discountAmount:10000,refundAmount:5000,netAmount:185000},lines:[line],evidence:[{fileVersionId:"da560000-0000-4000-8000-000000000001",displayName:"마감증빙.png"}],corrections:[],confirmedAt:"2026-08-13T10:00:00.000Z",updatedAt:"2026-08-13T10:00:00.000Z"};
const internalSales={...publicSales,internalMemo:"내부 메모",createdBy:{userId:principal.userId,displayName:principal.displayName}};
function repository(payload:unknown=internalSales){return {capabilities:vi.fn().mockResolvedValue({status:"OK",payload:{hotels:[{hotelId,hotelName:"서울호텔",canRead:true,canManage:true,canConfirm:true,canCorrect:true,ownerView:false}]}}),close:vi.fn(),command:vi.fn().mockResolvedValue({status:"CREATED",payload}),read:vi.fn().mockResolvedValue({status:"OK",payload})};}
function authService(){return {close:vi.fn(),resolvePrincipal:vi.fn(async()=>principal)} as never;}

describe("daily sales service and API",()=>{
 it("uses canonical DB command with opaque session context",async()=>{const repo=repository();const service=createDailySalesService(repo);await expect(service.create(principal,hotelId,{salesId,businessDate:"2026-08-13",memo:"내부 메모",lines:[line]},"sales-create-key")).resolves.toEqual(internalSales);expect(repo.command).toHaveBeenCalledWith(expect.objectContaining({action:"CREATE",companyId:principal.companyId,expectedVersion:0,hotelId,idempotencyKey:"sales-create-key",method:"POST",operationPath:`/api/hotels/${hotelId}/daily-sales`,resourceId:salesId,sessionId:principal.sessionId,sessionToken:principal.sessionToken}));});
 it("rejects private fields in owner projection",async()=>{const service=createDailySalesService(repository(publicSales));await expect(service.get(principal,hotelId,salesId)).resolves.toEqual(publicSales);const leaked=createDailySalesService(repository({...publicSales,internalMemo:"leak"}));await expect(leaked.get(principal,hotelId,salesId)).rejects.toMatchObject({code:"INTERNAL_ERROR",httpStatus:500});});
 it("maps locked, evidence, duplicate, total, and version errors",async()=>{for(const [status,code,httpStatus] of [["HOTEL_SALES_LOCKED","HOTEL_SALES_LOCKED",409],["HOTEL_SALES_EVIDENCE_REQUIRED","HOTEL_SALES_EVIDENCE_REQUIRED",422],["HOTEL_SALES_DUPLICATE_DATE","HOTEL_SALES_DUPLICATE_DATE",409],["HOTEL_SALES_TOTAL_MISMATCH","HOTEL_SALES_TOTAL_MISMATCH",422],["VERSION_CONFLICT","VERSION_CONFLICT",409]] as const){const repo=repository();repo.command.mockResolvedValueOnce({status,payload:null});const service=createDailySalesService(repo);await expect(service.confirm(principal,hotelId,salesId,{version:3,evidenceFileVersionIds:["da560000-0000-4000-8000-000000000001"]},`key-${status}`)).rejects.toMatchObject({code,httpStatus});}});
 it("serves capabilities, references, collection, detail, confirm and corrections",async()=>{const service={capabilities:vi.fn(async()=>({hotels:[{hotelId,hotelName:"서울호텔",canRead:true,canManage:true,canConfirm:true,canCorrect:true,ownerView:false}]})),references:vi.fn(async()=>({categories:[{id:categoryId,name:"객실매출"}],paymentMethods:[{id:paymentMethodId,name:"카드"}]})),list:vi.fn(async()=>({sales:[publicSales],pagination:{page:1,pageSize:20,total:1}})),get:vi.fn(async()=>publicSales),create:vi.fn(async()=>internalSales),update:vi.fn(async()=>internalSales),confirm:vi.fn(async()=>internalSales),correct:vi.fn(async()=>({...internalSales,version:4})),close:vi.fn()};const app=createApp({authService:authService(),dailySalesService:service});const h={"content-type":"application/json",cookie:"__Host-hotel_session=opaque-daily-sales-token","idempotency-key":"sales-route-key"};expect((await app.request("/api/daily-sales/capabilities",{headers:h})).status).toBe(200);expect((await app.request(`/api/hotels/${hotelId}/daily-sales/references`,{headers:h})).status).toBe(200);expect((await app.request(`/api/hotels/${hotelId}/daily-sales`,{headers:h})).status).toBe(200);expect((await app.request(`/api/hotels/${hotelId}/daily-sales/${salesId}`,{headers:h})).status).toBe(200);expect((await app.request(`/api/hotels/${hotelId}/daily-sales/${salesId}/confirm`,{method:"POST",headers:h,body:JSON.stringify({version:3,evidenceFileVersionIds:["da560000-0000-4000-8000-000000000001"]})})).status).toBe(200);expect((await app.request(`/api/hotels/${hotelId}/daily-sales/${salesId}/corrections`,{method:"POST",headers:h,body:JSON.stringify({version:3,reason:"현금매출 누락 정정",evidenceFileVersionIds:["da560000-0000-4000-8000-000000000002"],memo:null,lines:[line]})})).status).toBe(200);});
});
